v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
T {CACE testbench dccurrent} 610 -1150 0 0 0.6 0.6 {}
N 570 -100 630 -100 {
lab=VSUB}
N 520 -100 570 -100 {
lab=VSUB}
N 650 -670 650 -190 {
lab=vdd}
N 650 -670 990 -670 {
lab=vdd}
N 990 -670 990 -620 {
lab=vdd}
N 630 -100 990 -100 {
lab=VSUB}
N 990 -190 990 -160 {
lab=vss}
N 650 -130 650 -100 {
lab=VSUB}
N 840 -100 840 -80 {
lab=VSUB}
N 1220 -410 1270 -410 {
lab=out}
C {devices/lab_wire.sym} 990 -640 0 1 {name=p11 sig_type=std_logic lab=vdd}
C {devices/lab_wire.sym} 990 -170 0 1 {name=p24 sig_type=std_logic lab=vss}
C {devices/code_shown.sym} 20 -710 0 0 {name=CONTROL only_toplevel=false value=".control
op
set wr_singlescale
wrdata \{simpath\}/\{filename\}_\{N\}.data -I(Vvdd)
quit
.endc
"}
C {devices/code_shown.sym} 20 -980 0 0 {name=SETUP only_toplevel=false value="* CACE gensim simulation file \{filename\}_\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023
* Find the current through the amplifier under condition of static input

.include \{DUT_path\}

.lib \{PDK_ROOT\}/\{PDK\}/libs.tech/combined/sky130.lib.spice \{corner\}

.option TEMP=\{temperature\}
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {devices/vsource.sym} 650 -160 0 0 {name=Vvdd value="DC \{Vvdd\}" savecurrent=false}
C {devices/lab_pin.sym} 520 -100 0 0 {name=p1 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 990 -130 0 0 {name=Vvss value="DC \{Vvss\}" savecurrent=false}
C {devices/res.sym} 840 -50 0 0 {name=RSUB
value=0.01
device=resistor}
C {devices/gnd.sym} 840 -20 0 0 {name=l1 lab=GND}
C {/home/sai/analog-tests/resistor_divider/xschem/resistor_divider.sym} 750 -120 0 0 {name=x1}
C {devices/lab_wire.sym} 1270 -410 2 0 {name=p25 sig_type=std_logic lab=out}
